version: "3.9"

services:
  customerservice:
    build:
      context: ./CustomerService/CustomerService.Api
    ports:
      - "6002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Data Source=/data/customer.db"
    volumes:
      - customer_data:/data

  productservice:
    build:
      context: ./ProductService/ProductService.Api
    ports:
      - "6001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Data Source=/data/product.db"
    volumes:
      - product_data:/data

  orderservice:
    build:
      context: ./OrderService/OrderService.Api
    ports:
      - "6003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Data Source=/data/orders.db"
      # IMPORTANT: these URLs must be absolute for HttpClient calls inside docker
      CustomerService__BaseUrl: "http://customerservice:8080"
      ProductService__BaseUrl: "http://productservice:8080"
      PaymentService__BaseUrl: "http://paymentservice:8080"
    volumes:
      - orders_data:/data

  paymentservice:
    build:
      context: ./PaymentService/PaymentService.Api
    ports:
      - "6004:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Data Source=/data/payment.db"
    volumes:
      - payment_data:/data

volumes:
  customer_data:
  product_data:
  orders_data:
  payment_data: